version: '3'

services:
  languru-agent:
    image: languru:${LANGURU_VERSION:-dev}
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    container_name: languru-agent
    environment:
      - IS_PRODUCTION=${IS_PRODUCTION:-false}
      - IS_DEVELOPMENT=${IS_DEVELOPMENT:-true}
      - IS_TESTING=${IS_TESTING:-false}
      - PORT=${PORT:-80}
      - COLUMN_NAME=${COLUMN_NAME:-89}
    ports:
      - "8680:80"
    volumes:
      - ./languru:/app/languru
    command:
      - "agent"
      - "run"
    networks:
      - languru-network

  languru-llm-openai:
    image: languru:${LANGURU_VERSION:-dev}
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    container_name: languru-llm-openai
    environment:
      - IS_PRODUCTION=${IS_PRODUCTION:-false}
      - IS_DEVELOPMENT=${IS_DEVELOPMENT:-true}
      - IS_TESTING=${IS_TESTING:-false}
      - PORT=${PORT:-80}
      - AGENT_BASE_URL=${AGENT_BASE_URL:-http://languru-agent}
      - LLM_BASE_URL=http://languru-llm-openai:8682/v1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-xxxxxxxxxxxxxxxxxxxxxxxx}
      - COLUMN_NAME=${COLUMN_NAME:-89}
    ports:
      - "8682:80"
    volumes:
      - ./languru:/app/languru
    command:
      - "llm"
      - "run"
    networks:
      - languru-network
    depends_on:
      - languru-agent
    profiles:
      - openai
      - oai

networks:
  languru-network:
    driver: bridge
