version: '3'

services:
  languru-agent:
    image: languru:${LANGURU_VERSION:-dev}
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    container_name: languru-server
    environment:
      - IS_PRODUCTION=${IS_PRODUCTION:-false}
      - IS_DEVELOPMENT=${IS_DEVELOPMENT:-true}
      - IS_TESTING=${IS_TESTING:-false}
      - PORT=${PORT:-80}
      - COLUMN_NAME=${COLUMN_NAME:-89}
    ports:
      - "8680:80"
    volumes:
      - ./languru:/app/languru
    command:
      - "server"
      - "run"
    networks:
      - languru-network


networks:
  languru-network:
    driver: bridge
