version: '3'

services:
  languru-agent:
    image: languru:${LANGURU_VERSION:-dev}
    build:
      context: .
      dockerfile: docker/dockerfile.dev
    container_name: languru-server
    environment:
      - IS_PRODUCTION=${IS_PRODUCTION:-false}
      - IS_DEVELOPMENT=${IS_DEVELOPMENT:-true}
      - IS_TESTING=${IS_TESTING:-false}
      - PORT=${PORT:-80}
      - COLUMN_NAME=${COLUMN_NAME:-89}
      # OpenAI Clients API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-01}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
      - PPLX_API_KEY=${PPLX_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}

    ports:
      - "8680:80"
    volumes:
      - ./languru:/app/languru
    command:
      - "server"
      - "run"
    networks:
      - languru-network


networks:
  languru-network:
    driver: bridge
