site_name: Languru
repo_url: https://github.com/dockhardman/languru
repo_name: dockhardman/languru
edit_uri: edit/master/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
plugins:
  - git-authors
  - mkdocs-nav-weight
  - neoteroi.mkdocsoad
  - search
  - tags
  - git-committers:
      repository: dockhardman/languru
      branch: master
  - git-revision-date-localized:
      enable_creation_date: true
  - render_swagger:
      allow_arbitrary_locations: true
